<<<<<<< HEAD
import { ReactNode } from "react";
import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Inter } from "next/font/google";

import "@stream-io/video-react-sdk/dist/css/styles.css";
import "react-datepicker/dist/react-datepicker.css";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
=======
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
>>>>>>> d893d9c6da674d46a34c23440d8d0c5fa122122b

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "WebTeem",
  description: "Video calling App",
  icons: {
    icon: "/icons/logo.svg",
  },
=======
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> d893d9c6da674d46a34c23440d8d0c5fa122122b
};

export default function RootLayout({
  children,
<<<<<<< HEAD
}: Readonly<{ children: ReactNode }>) {
  return (
    <html lang="en">
      <ClerkProvider
        appearance={{
          layout: {
            socialButtonsVariant: "iconButton",
            // logoImageUrl: "/icons/yoom-logo.svg",
          },
          variables: {
            colorText: "#fff",
            colorPrimary: "#0E78F9",
            colorBackground: "#1C1F2E",
            colorInputBackground: "#252A41",
            colorInputText: "#fff",
          },
        }}
      >
        <body className={`${inter.className} bg-dark-2`}>
          <Toaster />
          {children}
        </body>
      </ClerkProvider>
=======
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-dark-2`}>{children}</body>
    </html>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-dark-2`}>{children}</body>
>>>>>>> d893d9c6da674d46a34c23440d8d0c5fa122122b
    </html>
  );
}
